- 
  hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - include: tasks/ssh.yaml
    - include: tasks/zsh-setup.yaml
    - include: tasks/misc.yaml
    - include: tasks/dotfiles.yaml
