- name:  Install stow
  community.general.homebrew:
    name:
      - stow
    state: present
  tags:
    - install
    - dotfiles

- name: Clone my dotfiles
  git:
    repo: "git@github.com:thuaung30/dotfiles.git"
    dest: "{{ lookup('env', 'HOME')}}/.dotfiles"
    accept_hostkey: yes
    key_file: "./.ssh/id_ed25519"
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  command:
    cmd: ./stowdis.sh
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  tags:
    - install
    - dotfiles

- name: Check that script path exists
  stat:
    path: /etc/paths.d/scripts
  register: script_stats
  tags:
    - install
    - dotfiles

- name: Set up scripts path
  ansible.builtin.copy:
    dest: /etc/paths.d/scripts
    content: |
      "lookup('env', 'HOME')/.config/scripts" 
  delegate_to: localhost
  become: yes
  when: script_stats.stat.exists == False
  tags:
    - install
    - dotfiles
