- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | xargs dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - install
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - install
    - ssh

- name: Decrypting ssh vault
  command:
    cmd: "ansible-vault decrypt id_ed25519 --output bruh"
    chdir: "{{ lookup('env', 'HOME') }}/.ssh"
  tags:
    - install
    - ssh
